services:
  # Development
  dev:
    build:
      target: development
      context: .
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}

  # Production service
  prod:
    build:
      target: production
      context: .
    ports:
      - '80:80'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
